# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Manual Go Build and Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v -o ./vstup-bot

    - name: Upload Go build
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: ./vstup-bot

    - name: Test
      run: go test ./... -json > TestResults.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: TestResults.json
